config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/OSTrails/FAIR_assessment_output_specification:
      branch: main
      repo: https://github.com/OSTrails/FAIR_assessment_output_specification.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/OSTrails/FAIR_assessment_output_specification git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-celadon-camel.sh
        container: qc.acc_flimsy-orchid-sparrow
  QC.Doc:
    repos:
      github.com/OSTrails/FAIR_assessment_output_specification find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-amber-llama.sh
        container: qc.doc_cheeky-lilac-dollar
      github.com/OSTrails/FAIR_assessment_output_specification git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cobalt-bobcat.sh
        container: qc.doc_tasty-cream-camel
      github.com/OSTrails/FAIR_assessment_output_specification markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-lemon-malamute.sh
        container: qc.doc_sleazy-gold-bonobo
  QC.Lic:
    repos:
      github.com/OSTrails/FAIR_assessment_output_specification licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-ecru-earwig.sh
        container: qc.lic_bluesy-periwinkle-buffalo
  QC.Sty:
    repos:
      github.com/OSTrails/FAIR_assessment_output_specification jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-khaki-walrus.sh
        container: qc.sty_muggy-khaki-yak
  QC.Ver:
    repos:
      github.com/OSTrails/FAIR_assessment_output_specification get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-pink-iguana.sh
        container: qc.ver_cheeky-sangria-fox
timeout: 5400
